repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.240
    hooks:
      - id: ruff

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args:
          - --quiet

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
