repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: python
        additional_dependencies:
          - venv-run==0.2.0
        entry: venv-run mypy custom_components
        types: [python]
        pass_filenames: false
        require_serial: true

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
