[tool.black]
target-version = ["py310"]

[tool.mypy]
python_version = "3.10"
enable_error_code = "ignore-without-code,redundant-self,truthy-iterable"
strict = true
warn_unreachable = true

[tool.ruff]
select = ["ALL"]
ignore = [
  "ANN", # Maybe sometime
  "COM", # Black
  "D203", # Black, ping/pong with D211
  "D213", # Ping/pong with D212
  #"E203", # Black, uncomment when/if ruff starts to support
  "E501", # Black
  "TCH", # Maybe sometime

]
fix = true
target-version = "py310"

[tool.ruff.isort]
combine-as-imports = true # Home Assistant preference
force-sort-within-sections = true # Home Assistant preference

[tool.pytest.ini_options]
testpaths = ["tests"]
norecursedirs = [".git", "testing_config"]
log_format = "%(asctime)s.%(msecs)03d %(levelname)-8s %(threadName)s %(name)s:%(filename)s:%(lineno)s %(message)s"
log_date_format = "%Y-%m-%d %H:%M:%S"
