[settings]
lockfile_platforms = [] # all here, even if local global config reduces the set

[tools]
committed = "1.1.11"
dprint = "0.55.2"
lefthook = "latest"
ruff = "0.15.22"
rumdl = "0.1.81"
typos = "1.48.0"

[env]
NOX_DEFAULT_VENV_BACKEND = "uv"
