name: Check

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "33 3 * * *"

jobs:
  hacs:
    runs-on: ubuntu-latest
    steps:
      - uses: hacs/action@d556e736723344f83838d08488c983a15381059a # 22.5.0
        with:
          category: integration
          ignore: brands information
  hassfest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: home-assistant/actions/hassfest@master

  lint:
    if: github.event_name != 'schedule'
    runs-on: ubuntu-latest
    steps:
      - uses: scop/common/force-color@main
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0 # for commit message checks
      - uses: astral-sh/setup-uv@61cb8a9741eeb8a550a1b8544337180c0fc8476b # v7.2.0
        with:
          activate-environment: true
      - name: Install Python dev dependencies
        run: uv pip install --upgrade --requirements requirements/dev-requirements.txt
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
      - name: Check code
        run: lefthook run pre-commit --all-files --no-tty
      - name: Check commit messages
        run: lefthook run commits-on-pr-branch --no-tty
        if: ${{ github.event_name == 'pull_request' }}
