name: HACS action

on:
  push:
  pull_request:
  schedule:
    - cron: "33 3 * * *"

jobs:
  hacs:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "hacs/action@main"
        with:
          category: "integration"
          ignore: "brands information"
