name: Release

on:
  push:
    branches:
      - main

jobs:
  release_please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@d1a8f221d7723166f48a584aebba00ef3f6febec # v4.1.4
        with:
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json
