name: Release

on:
  push:
    branches:
      - main

jobs:
  release_please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@e4dc86ba9405554aeba3c6bb2d169500e7d3b4ee # v4
        with:
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json
