name: "Release"

on:
  push:
    branches:
      - "main"

jobs:
  release_please:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "google-github-actions/release-please-action@v4"
        with:
          command: "manifest"
