name: Release

on:
  workflow_run:
    workflows:
      - "Check"
    branches:
      - "main"
    types:
      - "completed"

jobs:
  release_please:
    runs-on: "ubuntu-latest"
    if: "github.event.workflow_run.conclusion == 'success'"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "GoogleCloudPlatform/release-please-action@v3"
        with:
          release-type: "simple"
          pull-request-title-pattern: "chore: release${component} ${version}"
          extra-files:
            - type: "json"
              path: "custom_components/jatekukko/manifest.json"
              jsonpath: "$.version"
