name: Release

on:
  push:
    branches:
      - main

jobs:
  release_please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445 # v4.2.0
        with:
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json
